apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: demo-policy-generator
placementBindingDefaults:
  name: demo-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: demo-placement-rule
    clusterSelectors:
      matchExpressions:
        - key: data-protection
          operator: In
          values:
            - kasten
        - key: vendor
          operator: In
          values:
            - OpenShift
  remediationAction: inform
  severity: medium
policies:
  - name: policy-kasten-immutable-profiles
    manifests:
      - path: kasten-policies/kasten-immutable-location-profile.yaml
